### ISSUE TITLE
Please add collection category name to upload template 

### ISSUE THREAD

**Issue by Lanbot84** [atetevoortwis/pypypan#10]
The category names are: 
[[Category:Media from negatieven collectie Bonda RAA]]

Example: 
https://commons.wikimedia.org/wiki/File:Het_Spaansepad_met_de_gevel_van_J._Smit,_later_Geerts._-_FO1400041_-_RAA_Bonda.jpg

**Comment by atetevoortwis** [comment]
This should be added to the template in the Excel file used, and is not something to change/add to Pypypan.
