### ISSUE TITLE
'==Licentie==  

### ISSUE THREAD

**Issue by Lanbot84** [atetevoortwis/pypypan#9]
The ' in front of licentie should be removed because it prevents proper heading in wikitext being displayed. 
See: 
https://commons.wikimedia.org/wiki/File:Een_liggend_gezelschap_op_een_duinhelling._Links_zijn_het_strand_en_de_zee_zichtbaar._-_FO1400104_-_RAA_Bonda.jpg

**Comment by atetevoortwis** [comment]
This is part of the template in the Excel file used, and not something that Pypypan adds to the description. So the solution would be to fix it in the Excel file and upload again (the descriptions for the files already uploaded will be updated)
